### PR TITLE
Symfony7

### PR DESCRIPTION
**Pull request by cebe**
Run #203 with tests.

### CODE REVIEW

**Comment by tacman** [comment]
can you please accept this PR?  It simply allows the YAML component to be used in a Symfony 7 application.  If there are other issues, I'll submit PRs for them, but this is really tiny, and the Symfony YAML parser hasn't changed significantly in ages.

**Comment by cebe** [comment]
Sure, we will merge it as soon as tests are passing. Working on that.

**Comment by someniatko** [comment]
I'm glad you have returned, yay!

**Comment by NickBourque** [comment]
@cebe Any chance of tagging a version with this update? Currently appears to only be on master.

**Comment by SOHELAHMED7** [comment]
@NickBourque [1.8.0](https://github.com/cebe/php-openapi/releases/tag/1.8.0)

**Comment by NickBourque** [comment]
Thanks for the ping, @SOHELAHMED7

**Pull request merged**
