### PR TITLE
Rework CI 

### PR DESCRIPTION
**Pull request by simPod**
- Use ramsey/composer-install action
- ~Drop testing on multiple OSes as it's not relevant~
- Move timezone setting to bootstrap file
- Run standalone PHPStan and Code Style checks
- Bump justinrainbow/json-schema to v5.2 as it supports PHP 8.0
- Conflict with symfony/yaml `3.4.0 - 3.4.4 || 4.0.0 - 4.4.17 || 5.0.0 - 5.1.9 || 5.2.0` in order to prevent installing broken versions (especially this issue https://github.com/symfony/symfony/issues/39521)
- Run speccy through yarn

- [ ] I'don't know windows and not sure how to force it to understand `composer require symfony/yaml:"^5"`

image

### CODE REVIEW

**Comment by simPod** [comment]
@cebe I've been tweaking this for a while but now it works. CI is green. (with #145)

image

**Comment by cebe** [comment]
Thanks for your work on this one, I have one thing to discuss:

> Drop testing on multiple OSes as it's not relevant

Multiple OS as relevant to make sure loading of external files from references works. There were some bugs about this on windows systems. That said, I'd like to keep testing on windows and mac, at least  a combination of latest php and dependencies to make sure it works on these systems.

**Comment by simPod** [comment]
@cebe we're running macos and windows now. Would it suffice like this?

**Comment by simPod** [comment]
It indeed shows a failure https://github.com/cebe/php-openapi/runs/4693855168?check_suite_focus=true

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
