### PR TITLE
Format all code in readme using ```

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by cebe** [comment]
does not change anything as far as I see.

**Comment by simPod** [comment]
This was intended to be markdown compliant. Using indents for block formatting is not correct.

**Comment by cebe** [comment]
> Using indents for block formatting is not correct.

what makes you think this is not correct? 4 space indentation is a code block in markdown.

**Comment by simPod** [comment]
I guess it is. I don't remember anymore what was this about 🤷🏾‍♀️  I guess I encountered a renderer that did not support it as using ``` is more common.

**Pull request closed without merging**
