### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by tacman** [comment]
any downside to merging this?

**Comment by cebe** [comment]
Tests are failing on php 8.2 https://github.com/cebe/php-openapi/pull/212

**Comment by tacman** [comment]
yes, but that's not related to Symfony 7, is it?

**Comment by tacman** [comment]
Personally, I'd prefer to see all unsupported versions of Symfony dropped.  So ^5.4, ^6.4, ^7

If it's a new release, I'd even say just ^6.4 || ^7, since 5.4 is near EOL

**Comment by cebe** [comment]
> yes, but that's not related to Symfony 7, is it?

I did not know whether it's related or not so I wanted to wait for tests to pass.

> Personally, I'd prefer to see all unsupported versions of Symfony dropped. So ^5.4, ^6.4, ^7

what's the point in dropping versions that work fine, breaking someones code? Dropping old versions is fine if it is complicated to support these. For Symfony YAML I'd keep it as widely compatibly as possible.

**Comment by cebe** [comment]
Your commit is merged in #212, thanks!

**Comment by prajapati-kaushik** [comment]
@cebe: I suppose, brach merged but  a new version 7.1 release is pending.

**Pull request closed without merging**
